### PR TITLE
Fixed some bugs, mostly warnings, and significantly improved the perform...

### PR DESCRIPTION
**Pull request by brandon-garcia**
...ance of this module. Very large reports can now be generated without php memory crashes. However, the web page size of very large reports moves the bottleneck out of php and into the browser's ability to load pages with large amounts of data. I suggest pagination as a solution to this particular issue. I tried to minimize the number of changes made to the code base prior to committing. This code, prior to minimizing changes, is already being used on a production server at wheaton college. The minimizing changes shouldn't have significantly affected the impact of this commit aside from avoiding changing files where not necessary.

classes no longer being used:
- DynamicObject
- ReportGroupingColumn //unnecessary
- ReportSum //unnecessary

For sql database usage, the mysqli extension is used rather than raw function calls that lacked necessary functionality

I gutted the Object and DynamicObject classes because as far as this module is concerned, they made the code much more complex while having significant function call overhead for things that can be more easily done in child classes. I found the complicated type hierarchy to be an obstacle in improving the module.  I can't remember why I kept the Object class as it is now empty, but I probably ran into problems when I tried removing it altogether.

### CODE REVIEW

**Comment by jeffnm** [comment]
No, don't merge this yet. It looks like some bugs got introduced while cleaning it up and minimizing changes. We'll look into that and get this updated. Sorry for the delay.

**Comment by jeffnm** [comment]
Brandon, it looks like your commits from Feb 26 are what broke this pull request. Can you revert the master branch back to https://github.com/brandon-garcia/reports/commit/5791f12f2e156e4b6455a90ede5d1cab1c73245b

**Comment by brandon-garcia** [comment]
I'll talk to you about it tomorrow I think.

**Comment by benheet** [comment]
@jeffnm any update on this? after you've resolved and feel confident you can probably proceed with a merge since this has been sitting here for a while.

**Pull request merged**
